name: Uppdatera elpriser

on:
  schedule:
    - cron: "30 12 * * *"   # 12:30 UTC = 14:30 svensk tid
  workflow_dispatch:        # så du kan köra manuellt också

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installera beroenden
        run: pip install -r requirements.txt

      - name: Kör script för att hämta priser
        run: python fetch_nordpool.py

      - name: Commit & push uppdaterad data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Automatisk uppdatering av elpriser $(date)"
          git push
