name: Uppdatera elpriser

on:
  schedule:
    - cron: '30 12 * * *'   # körs varje dag kl 14:30 svensk tid (12:30 UTC)
  workflow_dispatch:        # kan även köras manuellt

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Hämta dagens datum
        id: today
        run: echo "date=$(date +'%Y/%m-%d')" >> $GITHUB_OUTPUT

      - name: Ladda ner dagens priser
        run: |
          URL="https://www.elprisetjustnu.se/api/v1/prices/${{ steps.today.outputs.date }}_SE3.json"
          echo "Hämtar $URL"
          curl -s "$URL" > data/today.json

      - name: Försök hämta morgondagens priser
        run: |
          TOMORROW=$(date -d tomorrow +'%Y/%m-%d')
          URL="https://www.elprisetjustnu.se/api/v1/prices/${TOMORROW}_SE3.json"
          echo "Hämtar $URL"
          curl -s "$URL" -o data/tomorrow.json || echo "Ingen morgondata än"

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/today.json data/tomorrow.json || true
          git commit -m "Uppdaterade priser $(date)" || echo "Inget att commit:a"
          git push
