name: Update Elpris Data

on:
  schedule:
    - cron: "30 13 * * *"   # Kör varje dag kl 14:30 svensk tid
  workflow_dispatch:        # Kan även köras manuellt

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Fetch today's and tomorrow's prices
        run: |
          python3 <<EOF
          import requests, datetime, json
          from pathlib import Path

          base_url = "https://www.elprisetjustnu.se/api/v1/prices"

          now = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=2)))  # svensk tid
          year, month, day = now.year, f"{now.month:02d}", f"{now.day:02d}"
          today_url = f"{base_url}/{year}/{month}-{day}_SE3.json"

          tomorrow = now + datetime.timedelta(days=1)
          y2, m2, d2 = tomorrow.year, f"{tomorrow.month:02d}", f"{tomorrow.day:02d}"
          tomorrow_url = f"{base_url}/{y2}/{m2}-{d2}_SE3.json"

          outdir = Path("data")
          outdir.mkdir(exist_ok=True)

          def fetch(url, filename):
              r = requests.get(url)
              if r.status_code == 200:
                  with open(outdir / filename, "w") as f:
                      f.write(r.text)
                  print(f"✅ Saved {filename}")
              else:
                  print(f"⚠️ Could not fetch {url}, status {r.status_code}")

          fetch(today_url, "today.json")
          fetch(tomorrow_url, "tomorrow.json")
          EOF

      - name: Commit and push data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/*.json
          git commit -m "Update elpris data" || echo "No changes"
          git push
