name: Uppdatera elpriser

on:
  schedule:
    # Kör varje dag kl 14:30 svensk tid (12:30 UTC)
    - cron: '30 12 * * *'
  workflow_dispatch: # så att du kan köra manuellt via GitHub också

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta koden
        uses: actions/checkout@v4

      - name: Sätt upp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Installera beroenden
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kör script för att hämta elpriser
        run: |
          python fetch_nordpool.py

      - name: Commit och pusha uppdaterad data.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Automatisk uppdatering av data.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
