name: Update electricity prices

on:
  schedule:
    - cron: "30 12 * * *"   # kör varje dag 14:30 svensk tid (12:30 UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run fetch script
        run: |
          source .venv/bin/activate
          python fetch_nordpool.py

      - name: Split today and tomorrow JSON
        run: |
          mkdir -p data
          python - <<'EOF'
          import json
          from datetime import datetime

          # Läs in huvudfilen
          with open("data.json", "r", encoding="utf-8") as f:
              raw = json.load(f)

          def make_day(hours, prices):
              out = []
              for h, p in zip(hours, prices):
                  out.append({
                      "time_start": h,
                      "SEK_per_kWh": round(p / 100.0, 5)  # konvertera öre -> SEK
                  })
              return out

          # Spara idag
          today = make_day(raw["hours"], raw["prices_ore_per_kwh"])
          with open("data/today.json", "w", encoding="utf-8") as f:
              json.dump(today, f, ensure_ascii=False, indent=2)

          # Spara imorgon (om finns)
          if "tomorrow" in raw and "hours" in raw["tomorrow"]:
              tomorrow = make_day(raw["tomorrow"]["hours"], raw["tomorrow"]["prices_ore_per_kwh"])
              with open("data/tomorrow.json", "w", encoding="utf-8") as f:
                  json.dump(tomorrow, f, ensure_ascii=False, indent=2)
          EOF

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json data/today.json data/tomorrow.json
          git commit -m "Update electricity prices"
          git push
