name: Uppdatera elpris-data

on:
  schedule:
    - cron: "30 12 * * *"   # kör 14:30 svensk tid (GitHub kör UTC)
  workflow_dispatch:        # gör det även manuellt via GitHub-knapp

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Hämta data från API
        run: |
          python <<EOF
          import requests, json, datetime, pytz

          url = "https://www.elprisetjustnu.se/api/v1/prices.json?zone=SE3"
          r = requests.get(url)
          r.raise_for_status()
          data = r.json()

          # Sortera på starttid
          data.sort(key=lambda x: x["time_start"])

          # Idag
          today = [d for d in data if d["time_start"].startswith(datetime.datetime.now(pytz.timezone("Europe/Stockholm")).strftime("%Y-%m-%d"))]

          # Imorgon
          tomorrow_date = (datetime.datetime.now(pytz.timezone("Europe/Stockholm")) + datetime.timedelta(days=1)).strftime("%Y-%m-%d")
          tomorrow = [d for d in data if d["time_start"].startswith(tomorrow_date)]

          # Spara idag
          with open("data/today.json", "w") as f:
              json.dump(today, f, indent=2, ensure_ascii=False)

          # Spara imorgon (om finns)
          if tomorrow:
              with open("data/tomorrow.json", "w") as f:
                  json.dump(tomorrow, f, indent=2, ensure_ascii=False)
          EOF

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Uppdaterade elpris-data $(date +'%Y-%m-%d %H:%M:%S')" || echo "Inget att committa"
          git push
